### ISSUE TITLE
Performance improvements (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#214]
This is an Epic for all the performance tasks.

```[tasklist]
### Epic Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/23
- [ ] https://github.com/aquarist-labs/ceph/pull/81
- [ ] https://github.com/aquarist-labs/ceph/pull/124
- [ ] https://github.com/aquarist-labs/s3gw/issues/203
- [ ] https://github.com/aquarist-labs/ceph/pull/65
```

Performance reports: https://aquarist-labs.github.io/s3gw-perf-reports/

**Comment by jhmarina** [comment]
We're currently addressing the issues related to performance by reporting a bug
