### ISSUE TITLE
⛰ Expiration lifecycle management - versioned/unversioned

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#215]
This is an Epic for all the Lifecycle management tasks. Epic tasks:

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/187
- [ ] https://github.com/aquarist-labs/s3gw/issues/322
- [ ] https://github.com/aquarist-labs/s3gw/issues/349
```

**Comment by jhmarina** [comment]
The initial work in Lifecycle was already done. We can close this Epic and create a new one when we decide to improve lifecycle
