### ISSUE TITLE
Documentation (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#250]
This Epic groups all issues related to the revision and improvements of the documentation. The issues are:

```[tasklist]
### Documentation changes/improvements
- [ ] https://github.com/aquarist-labs/s3gw/issues/20
- [ ] https://github.com/aquarist-labs/s3gw/issues/21
- [ ] https://github.com/aquarist-labs/s3gw/issues/22
- [ ] https://github.com/aquarist-labs/s3gw/issues/81
- [ ] https://github.com/aquarist-labs/s3gw/issues/98
- [ ] https://github.com/aquarist-labs/s3gw/issues/99
- [ ] https://github.com/aquarist-labs/s3gw/issues/147
- [ ] https://github.com/aquarist-labs/s3gw/issues/151
- [ ] https://github.com/aquarist-labs/s3gw/issues/192
- [ ] https://github.com/aquarist-labs/s3gw/issues/251
- [ ] https://github.com/aquarist-labs/s3gw/issues/281
```

**Comment by jhmarina** [comment]
closing this Epic as most of the documentation work is already done.
