### ISSUE TITLE
Object listing (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#256]
## More information

```[tasklist]
### Tasks
- [ ] 
- [ ] https://github.com/aquarist-labs/s3gw/issues/509
- [ ] https://github.com/aquarist-labs/s3gw/issues/642
- [ ] https://github.com/aquarist-labs/s3gw/issues/643
- [ ] https://github.com/aquarist-labs/s3gw/issues/647
- [ ] https://github.com/aquarist-labs/s3gw/issues/644
```
