### ISSUE TITLE
UI: Implement an E2E suite for testing the UI (Epic)

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#292]
```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/520
- [ ] https://github.com/aquarist-labs/s3gw/issues/578
- [ ] https://github.com/aquarist-labs/s3gw/issues/773
```

**Comment by votdev** [comment]
@Ameenasuhani Is the whole UI now covered by E2E tests? is there anything missing?

**Comment by Ameenasuhani** [comment]
@votdev the scope of this is vast as any new changes to UI add scope for further tests. Coverage wise it seems pretty decent to me.

The current coverage includes
- Admin operations
- bucket operations 
- object operations
- user operations
- dashboard
- notification 
- language tests have been added

**Comment by jecluis** [comment]
@Ameenasuhani can you update us on the progress of this issue?

**Comment by Ameenasuhani** [comment]
@jecluis we are tracking changes under confluence here https://confluence.suse.com/display/LON/s3gw+Test+Plans

**Comment by Ameenasuhani** [comment]
Closing this epic as the scope of this is vast. After discussion with @vmoutoussamy the plan is to create per release based e2e testing epic and taking it to closure.
