### ISSUE TITLE
COSI controller (Epic)

### ISSUE THREAD

**Issue by l-mb** [s3gw-tech/s3gw#398]
### What needs to be done

Provide a `s3gw-cosi` controller (implementing Bucket and BucketAccess management via Kubernetes CRDs).

COSI is currently still in Alpha and might be an opportunity for upstream involvement.

### Why it needs to be done

Automated deployment of s3gw-based object storage in a Kubernetes native way.

### Additional Information

- https://github.com/kubernetes-sigs/container-object-storage-interface-spec
- https://github.com/ceph/ceph-cosi (rather dated)
- https://blog.min.io/kubernetes-csi-and-cosi-a-symbiotic-relationship/ (competition)
- https://github.com/longhorn/longhorn/issues/4154 (Longhorn issue for this)

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/433
- [ ] https://github.com/aquarist-labs/s3gw/issues/437
- [ ] https://github.com/aquarist-labs/s3gw/issues/436
- [ ] https://github.com/aquarist-labs/s3gw/issues/438
- [ ] https://github.com/aquarist-labs/s3gw/issues/439
- [ ] https://github.com/aquarist-labs/s3gw/issues/494
- [ ] https://github.com/aquarist-labs/s3gw/issues/495
- [ ] https://github.com/aquarist-labs/s3gw/issues/511
```

**Comment by giubacc** [comment]
We have currently all tasks marked as done; this doesn't mean that this work is complete.

1. We have to improve tests to cover all the scenarios we want to support for COSI.
2. We currently have some idea from Ceph cosi upstream that could be integrated downstream: https://github.com/ceph/ceph-cosi/pull/14
3. Work on COSI could be a good integration project for Epinio project (there is a significant need for Epinio users to have an S3 provider out-of-the-box)

**Comment by giubacc** [comment]
@jecluis I guess this could be closed
