### ISSUE TITLE
⛰ UI: Implement Object explorer (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#44]
The intention of the explorer UI is to allow an user to manage its own buckets.

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/144
- [ ] https://github.com/aquarist-labs/s3gw/issues/146
- [ ] https://github.com/aquarist-labs/s3gw/issues/167
- [ ] https://github.com/aquarist-labs/s3gw/issues/241
```

# Questions
- Do we want to use the same app for the administration/user UI?
- If so, how to determine how the user wants to log in? The options are the 'Admin UI' or the 'User UI'. One solution would be to add a drop-down box where the user can choose the log-in mode (e.g. `Admin` and `User`). The log in process then should check if the required privileges of the user matches the specified mode. The difficult thing here is that everything has to be done in the UI/browser because there is no back-end that is responsible for that, except we are implementing something in the RGW API as a dedicated end-point (but that does not fit into the current state of the API/project).

**Comment by jhmarina** [comment]
This will be needed to be split into several issues. @jhmarina will create the epic.

**Comment by votdev** [comment]
Please feel free to add additional ideas that should be included in the `Object explorer UI` (user mode).

**Comment by votdev** [comment]
@jhmarina I think we can close that as finished.

**Comment by 0xavi0** [comment]
I'm closing this as all sub-tasks are closed.
