### ISSUE TITLE
Longhorn controller (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#470]
### What needs to be done

Develop an endpoint controller component responsible for managing the deployment of s3gw pods in Longhorn. The controller should create and manage both the `s3gw` endpoint and the `s3gw-ui`.

### Why it needs to be done

The endpoint controller will provide the necessary functionality to create and manage the s3gw endpoint and the s3gw-ui in Longhorn.

### Acceptance Criteria

The controller should be capable of creating and managing s3gw pods, including the `s3gw` endpoint and the `s3gw-ui`.

### Additional information

[Longhorn Enhancement Proposal](https://github.com/longhorn/longhorn/pull/5832/files#diff-9484182b9875e61b914f175a8be29e1dc13ba51b192ded5d64a461f261dfb4f2)

### Tasks
- [ ] #625
- [ ] #627
- [ ] #541

### Implement the Longhorn Controller
- [x] Implement CRDs and generated Code
- [x] Implement command line options
- [x] Implement the control loop
- [x] Implement deployment mechanism
- [ ] https://github.com/aquarist-labs/s3gw/issues/634
- [ ] https://github.com/aquarist-labs/s3gw/issues/635
- [x] Implement uninstall hooks
- [ ] https://github.com/aquarist-labs/s3gw/issues/544
- [ ] Implement integration tests
- [ ] Implement gotests/unittests with mock API
- [x] Implement control logic ensuring filesystem is always XFS with reflinks
- [ ] Implement update/modification mechanism
- [ ] https://github.com/aquarist-labs/s3gw/issues/711
- [ ] https://github.com/aquarist-labs/s3gw/issues/712

**Comment by jhmarina** [comment]
@jecluis will add tasks to this Epic once he evaluates the work that needs to be done.

**Comment by asettle** [comment]
@m-ildefons will be conducting some preliminary investigations into testing up an environment suitable for developing and testing the controller. Adding Moritz to this ticket temporarily so that he can get this work done.

Ticket to be reassigned to Joao once he returns from vacation. It may work best to add a task to this ticket.

**Comment by jecluis** [comment]
Spoke with @m-ildefons this morning. He'll continue working on this. I'll take over should the need come up.

**Comment by m-ildefons** [comment]
For the time being, I'll manage the code here:
https://github.com/m-ildefons/longhorn/tree/wip/object-endpoint
https://github.com/m-ildefons/longhorn-manager/tree/wip/object-endpoint

**Comment by m-ildefons** [comment]
These are the PRs open, which implement the LH Controller:
Longhorn: https://github.com/longhorn/longhorn/pull/6640
Longhorn Manager: https://github.com/longhorn/longhorn-manager/pull/2136
Longhorn UI: https://github.com/longhorn/longhorn-ui/pull/649
Longhorn Engine: https://github.com/longhorn/longhorn-engine/pull/934
Backupstore: https://github.com/longhorn/backupstore/pull/148
Longhorn Instance Manager: https://github.com/longhorn/longhorn-instance-manager/pull/285
Integration Tests: https://github.com/longhorn/longhorn-tests/pull/1523

**Comment by jecluis** [comment]
LH integration is no longer part of the plan.
