### ISSUE TITLE
Versioning improvements (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#514]
### What needs to be done
We need to implement versioning following [this](https://github.com/aquarist-labs/s3gw/pull/497) ADR.

### Why it needs to be done
The actual versioning implementation is incomplete and doesn't follow all of the S3 standards. 

- We need to differentiate between delete markers and deleted versions.
- We need to be able to delete specific versions (non supported now and needed by lifecycle management for noncurrent versions)

### Acceptance Criteria

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/480
- [ ] https://github.com/aquarist-labs/s3gw/issues/472
- [ ] https://github.com/aquarist-labs/s3gw/pull/497
- [ ] https://github.com/aquarist-labs/s3gw/issues/547
- [ ] https://github.com/aquarist-labs/s3gw/issues/539
- [ ] https://github.com/aquarist-labs/s3gw/issues/526
- [ ] https://github.com/aquarist-labs/s3gw/issues/550
- [ ] https://github.com/aquarist-labs/s3gw/issues/378
```
