### ISSUE TITLE
s3gw UI accessible in Longhorn for volume details (Epic)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#540]
### What needs to be done
Add a link in the Longhorn user interface that allows users to access the s3gw UI in the volume details. It serves as an intermediate step towards the full integration of s3gw into the Longhorn UI. The expected features for the UI are:
- Bucket management
  - Create and delete a bucket
- Bucket access management
  - Ensure the user can create and delete/revoke bucket credentials (persistent and secure)
  - Ensure access management is through secret and access keys (and stored securely)

Although the s3gw UI will be loaded separately, it should closely resemble the Longhorn UI to ensure a seamless and cohesive user experience.

### Acceptance Criteria

- A link in the Longhorn user interface provides access to the s3gw UI for volume details.
- Clicking on the link opens the s3gw UI in a new tab or window.
- The s3gw UI reflects the design principles, visual elements, and layout of the Longhorn UI to maintain UI consistency.
- The s3gw UI includes the following expected features:
   - Bucket Management:
      - Users can create and delete buckets.
   - Bucket Access Management:
      - Users can create, delete, and revoke bucket credentials.
      - Bucket credentials are securely stored and managed.
      - Access management is implemented using secret and access keys.

### Additional Information

* This Epic depends on https://github.com/aquarist-labs/s3gw/issues/540
* https://confluence.suse.com/display/RES/Longhorn-s3gw+Integration+Plan#Longhorns3gwIntegrationPlan-%22Experimental%22Schedule

```[tasklist]
### My tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/552
- [ ] Enable s3gw set up from Longhorn volume
- [ ] Add link to s3gw UI in Longhorn volume
```

**Comment by jhmarina** [comment]
I'm closing this Epic. We've made significant advances in [the LH controller work](https://github.com/aquarist-labs/s3gw/issues/470) and will focus on the [Longhorn UI support epic](https://github.com/aquarist-labs/s3gw/issues/541)
