### ISSUE TITLE
UI/Backend: Expose API endpoints required by the UI (Epic)

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#593]
### What needs to be done

We need to expose as many API endpoints to the UI as it may need.

### Why it needs to be done

This is the whole point for the `s3gw-ui` backend existence: provide the UI with access to `s3gw`. We need proper APIs to ensure  proper access.

### Acceptance Criteria

The `s3gw-ui` backend is on API parity with what the UI currently needs to shift from communicating directly with `s3gw` to communicating with the backend and using its API endpoints.

### Additional Information

Moving the UI to using the `s3gw-ui` backend API endpoints should be an issue by itself.

Additionally, this issue should list all the sub-tasks required to achieve API parity.

```[tasklist]
## Tasks
- [ ] https://github.com/aquarist-labs/s3gw-ui/pull/216
- [ ] https://github.com/aquarist-labs/s3gw/issues/606
- [ ] https://github.com/aquarist-labs/s3gw/issues/607
- [ ] https://github.com/aquarist-labs/s3gw/issues/608
- [ ] https://github.com/aquarist-labs/s3gw/issues/610
```

**Comment by votdev** [comment]
Are https://github.com/aquarist-labs/s3gw/issues/388 and this epic more or less equivalent? Can we close one?

**Comment by jecluis** [comment]
I think is an Epic that is part of an Epic of Epics - #388 being the latter. I believe both exist in their own right, even if this looks a bit confusing.

**Comment by jecluis** [comment]
@votdev I think once https://github.com/aquarist-labs/s3gw/pull/708 is merged, we are in a good place to consider this issue concluded. Thoughts?

**Comment by jecluis** [comment]
considering this epic as done.
