### ISSUE TITLE
[Backlog] [LH] Test- and development environment for LH

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#625]
### What needs to be done

Exploration of what is needed to develop and test Longhorn, in particular with the integration work of s3gw in mind.
This may include a local setup on a workstation or a setup shared between developers.

### Acceptance Criteria

Capability to build, deploy and test LH with the s3gw integrated.

```[tasklist]
### Tasks
- [x] Longhorn Manager Unittests
- [x] Longhorn Manager Integration Tests
- [ ] Longhorn UI Tests
- [x] Test Environment
```

**Comment by m-ildefons** [comment]
See for reference:
https://github.com/longhorn/longhorn-tests/pull/512
https://github.com/longhorn/longhorn-tests/pull/496

**Comment by m-ildefons** [comment]
Test environment has been set up on some old nodes previously used in SES testing.
Unit- and integration tests are explored and it's clear what needs to be done, but it's not completed just yet. UI tests still need to be explored.
Unit tests: https://github.com/longhorn/longhorn-manager/pull/2136/files#diff-bad3c4fb64a4b645a5ac4da2e49574f6f3d495388e2aeef90a495d81ac7e8491
Integration tests: https://github.com/longhorn/longhorn-tests/pull/1523
