### ISSUE TITLE
Retry Read-Then-Write Transactions (Epic)

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#645]
### What needs to be done

Now that we have a retry utility, add retries to transactions that may collide and fail. Especially everything that is in the LC path as there aren't any client side retries possible.

Transactions:
- [x] SQLiteMultipart::create_or_reset_part **retry**
- [x] SQLiteMultipart::remove_multiparts_by_bucket_id_transact **retry**
- [x] SQLiteMultipart::remove_done_or_aborted_multiparts_transact  **retry**
- [x] SQLiteVersionedObjects::store_versioned_object_if_state **write transact**
- [x] SQLiteVersionedObjects::store_versioned_object_delete_committed_transact_if_state **retry**
- [x] SQLiteVersionedObjects::delete_version_and_get_previous_transact **write transact**
- [ ] SQLiteVersionedObjects::add_delete_marker_transact
- [x] SQLiteVersionedObjects::create_new_versioned_object_transact **retry**
- [x] SQLiteVersionedObjects::remove_deleted_versions_transact **retry**
- [x] SQLiteMultipart::abort_multiparts_by_bucket_id **write transact**
- [x] SQLiteMultipart::finish_part **write transact**
- [x] SQLiteMultipart::abort **write transact**
- [x] SQLiteMultipart::mark_complete **write transact**
- [x] SQLiteMultipart::mark_aggregating **write transact**
- [x] SQLiteMultipart::mark_done **write transact**

### Why it needs to be done

Either crashes or client retries (performance problem) due to transaction aborts bubbling up to the exception handler of last resort:

```
2023-08-14T18:51:02.559+0200 7fee24b746c0  0 req 0 0.030000690s s3:put_obj !!! BUG Unhandled exception while executing operation put_obj: database is locked: database is locked. replying internal error
```

#### rgw::sal::sfs::sqlite::SQLiteVersionedObjects::delete_version_and_get_previous_transact

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff5892b43 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff5841266 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5829897 in __GI_abort () at abort.c:79
#4  0x00007ffff5aacc17 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff5abc23c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff5abc2a7 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff5abc508 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x555557f00138 <typeinfo for std::system_error@GLIBCXX_3.4.11>,
    dest=0x7ffff5ae86d0 <std::system_error::~system_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x0000555557900c7e in rgw::sal::sfs::sqlite::SQLiteVersionedObjects::delete_version_and_get_previous_transact (this=this@entry=0x7fffeaff0580,
    id=<optimized out>) at /compile/s3gw/src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc:357
#9  0x00005555578e1204 in rgw::sal::sfs::Bucket::_undelete_object (this=this@entry=0x55555efd1810,
    objref=std::shared_ptr<rgw::sal::sfs::Object> (use count 3, weak count 0) = {...}, key=..., sqlite_versioned_objects=..., last_version=...)
    at /compile/s3gw/src/rgw/driver/sfs/types.cc:378
#10 0x00005555578e15d8 in rgw::sal::sfs::Bucket::delete_object (this=this@entry=0x55555efd1810,
    objref=std::shared_ptr<rgw::sal::sfs::Object> (use count 3, weak count 0) = {...}, key=..., versioned_bucket=versioned_bucket@entry=true,
    delete_marker_version_id="") at /compile/s3gw/src/rgw/driver/sfs/types.cc:334
#11 0x00005555578ddda7 in rgw::sal::SFSObject::SFSDeleteOp::delete_obj (this=0x55555f164380, dpp=<optimized out>, y=...)
    at /compile/s3gw/src/rgw/driver/sfs/object.cc:170
#12 0x00005555576f2c99 in remove_expired_obj (dpp=<optimized out>, oc=..., remove_indeed=remove_indeed@entry=true,
    event_type=event_type@entry=rgw::notify::ObjectExpirationDeleteMarker) at /compile/s3gw/src/common/async/yield_context.h:46
#13 0x000055555770548e in LCOpAction_DMExpiration::process (this=<optimized out>, oc=...) at /compile/s3gw/src/rgw/rgw_lc.cc:1192
#14 0x00005555576f389d in LCOpRule::process (this=this@entry=0x7fffeaff1128, o=..., dpp=<optimized out>, wq=wq@entry=0x55555877b990)
    at /compile/s3gw/src/rgw/rgw_lc.cc:1494
#15 0x00005555576f3e60 in operator() (__closure=<optimized out>, wk=0x555558793d10, wq=0x55555877b990, wi=...) at /compile/s3gw/src/rgw/rgw_lc.cc:1586
#16 0x00005555576f4070 in std::__invoke_impl<void, RGWLC::bucket_lc_process(std::string&, LCWorker*, time_t, bool)::<lambda(RGWLC::LCWorker*, WorkQ*, WorkItem&)>&, RGWLC::LCWorker*, WorkQ*, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry>&> (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#17 std::__invoke_r<void, RGWLC::bucket_lc_process(std::string&, LCWorker*, time_t, bool)::<lambda(RGWLC::LCWorker*, WorkQ*, WorkItem&)>&, RGWLC::LCWorker*, WorkQ*, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry>&> (__fn=...)
    at /usr/include/c++/12/bits/invoke.h:111
#18 std::_Function_handler<void(RGWLC::LCWorker*, WorkQ*, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry>&), RGWLC::bucket_lc_process(std::string&, LCWorker*, time_t, bool)::<lambda(RGWLC::LCWorker*, WorkQ*, WorkItem&)> >::_M_invoke(const std::_Any_data &, RGWLC::LCWorker *&&, WorkQ *&&, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry> &) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>, __args#2=...) at /usr/include/c++/12/bits/std_function.h:290
#19 0x00005555576fe459 in std::function<void (RGWLC::LCWorker*, WorkQ*, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry>&)>::operator()(RGWLC::LCWorker*, WorkQ*, boost::variant<void*, std::tuple<LCOpRule, rgw_bucket_dir_entry>, std::tuple<lc_op, rgw_bucket_dir_entry>, rgw_bucket_dir_entry>&) const (this=this@entry=0x55555877ba70, __args#0=<optimized out>, __args#1=<optimized out>,
    __args#1@entry=0x55555877b990, __args#2=...) at /usr/include/c++/12/bits/std_function.h:591
#20 0x0000555557702bd5 in WorkQ::entry (this=0x55555877b990) at /compile/s3gw/src/rgw/rgw_lc.cc:754
#21 0x00007ffff73d05cf in Thread::entry_wrapper (this=0x55555877b990) at /compile/s3gw/src/common/Thread.cc:87
#22 0x00007ffff73d05e7 in Thread::_entry_func (arg=<optimized out>) at /compile/s3gw/src/common/Thread.cc:74
#23 0x00007ffff5890c64 in start_thread (arg=<optimized out>) at pthread_create.c:444
#24 0x00007ffff5918550 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

```
S3_USE_SIGV4=1 S3TEST_CONF=/compile/s3gw/qa/rgw/store/sfs/tests/fixtures/s3tests.conf pytest -v -- s3tests_boto3/functional/test_s3.py::test_lifecycle_deletemarker_expiration
gdb --args bin/radosgw --no-mon-config --conf ~/WORKSPACE/dev-ceph-rgw/ceph-rgw.conf -d --rgw-lc-debug-interval 10 --rgw-sfs-sqlite-profile 1 --rgw-sfs-data-path=/compile/tmp/sfs --rgw-backend-store sfs --debug-rgw 25 --rgw-frontends 'beast port=7480, status bind=0.0.0.0 port=9090' --rgw_crypt_require_ssl=false --plugin_crypto_accelerator doesnotexist --rgw_crypt_s3_kms_backend testing --rgw_crypt_s3_kms_encryption_keys "testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo= testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=" --rgw_crypt_sse_s3_backend 'testingg' --rgw_crypt_default_encryption_key "4YSmvJtBv0aZ7geVgAsdpRnLBEwWSWlMIGnRS8a9TSA=" | tee last.log
```

**Comment by jecluis** [comment]
@irq0 do we have related PRs for this issue? Or something planned?

**Comment by irq0** [comment]
> @irq0 do we have related PRs for this issue? Or something planned?

This is a bit of a pseudo epic of the "ensure that all transactions are OK" kind.
`SQLiteVersionedObjects::add_delete_marker_transact` is WIP.

**Comment by jecluis** [comment]
ack, thanks for the clarification :)

Making it an Epic then.
