### ISSUE TITLE
Garbage collection (Epic)

### ISSUE THREAD

**Issue by jecluis** [s3gw-tech/s3gw#7]
This issue is an epic. Here are its subtasks:

```[tasklist]
### Issues
- [ ] #165 
- [ ] #358 
- [ ] https://github.com/aquarist-labs/s3gw/issues/357
- [ ] https://github.com/aquarist-labs/s3gw/issues/393
- [ ] https://github.com/aquarist-labs/s3gw/issues/483
- [ ] https://github.com/aquarist-labs/s3gw/issues/604
- [ ] https://github.com/aquarist-labs/s3gw/issues/657
```

**Comment by jhmarina** [comment]
<s>This is most likely an epic. @jhmarina will create it. 
We'll probably need to create issues and it'll be very likely spread across several milestones (0.8.0, 0.9.0 at least)</s>
