### ISSUE TITLE
Planning for v0.23.0

### ISSUE THREAD

**Issue by vmoutoussamy** [s3gw-tech/s3gw#801]
P0

```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/766
- [ ] https://github.com/aquarist-labs/s3gw/issues/766
```
```[tasklist]
### Tasks
- [ ] https://github.com/aquarist-labs/s3gw/issues/766
```

**Comment by vmoutoussamy** [comment]
this was just a test

**Comment by vmoutoussamy** [comment]
closing
